### ISSUE TITLE
Could not find artifact com.weiwan.dsp:dsp-extends-plugins:jar:1.0.0 in central

### ISSUE THREAD

**Issue by wikke** [WeiWan5675/Flink-DSP#1]
运行`mvn clean install -DskipTests`报错：

Could not find artifact com.weiwan.dsp:dsp-extends-plugins:jar:1.0.0 in central (https://repo.maven.apache.org/maven2)

应该是central没有这个jar包

**Comment by WeiWan5675** [comment]
https://github.com/WeiWan5675/Flink-DSP-Plugins 
在这个库
